### ISSUE TITLE
Update README to include the Github Packages credentials information

### ISSUE THREAD

**Issue by axymthr** [xebia-os/xebia-archunit-extension#4]
Copy some of the content from the https://github.com/xebia-os/spring-boot-react-maven-starter README to make it easier for people to include this project's dependencies without having to go through Github docs for credentials, etc.

**Comment by shekhargulati** [comment]
@awkshwayrd this is not required now. I have published package on Bintray. Now, we can use my simply adding a repo and the dependency. I have also updated the starter code. Please close this if you are fine.

**Comment by axymthr** [comment]
Closing as this is no longer needed.
